--- #YAML:1.0
name:               subs-auto
version:            0.05
abstract:           Read barewords as subroutine names.
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    Carp:             0
    perl:             5.01
    Symbol:           0
    Variable::Magic:  0.08
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/ReportBug.html?Queue=subs-auto
    homepage:    http://search.cpan.org/dist/subs-auto/
    license:     http://dev.perl.org/licenses/
    repository:  http://git.profvince.com/?p=perl%2Fmodules%2Fsubs-auto.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
